server:
  port: ":8080"

hdu_api:
  base_url: "https://skl.hdu.edu.cn/api"
  timeout_seconds: 60

ai_service:
  api_key: "sk-*****" 
  base_url: "https://api.deepseek.com"
  model: "deepseek-chat"
  timeout_seconds: 120

database:
  json_path: "./database.json"
  answer_bank_path: "./answer_bank.json"

cors:
  allowed_origins: ["http://localhost:5173", "http://127.0.0.1:5173"]